site_name: fcp7xml-to-unreal
# site_description: 'Filter FCP7 XML files exported from Editing applications so that Unreal will import them.'
repo_url: https://github.com/nick-animation-studio/fcp7xml-to-unreal
#docs_dir: .
#site_dir: ../site
# default branch is main instead of master now on github
edit_uri : ./edit/main/docs
nav:
    - Home: index.md
    - Configuration: configuration.md
    - Film Language: film_language.md
    - Marking Shots: marking_shots.md

theme: readthedocs

markdown_extensions:
  # - pymdownx.highlight  # see https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#highlight
  # - pymdownx.superfences # same as above as well as code blocks inside other blocks
  # - admonition  # to add notes such as http://squidfunk.github.io/mkdocs-material/extensions/admonition/
#  - codehilite:
#      guess_lang: false
  - toc:
      permalink: true