audio:
  music_track_prefix: "Music"
  sfx_track_prefix: "SFX"
  track_colors:
    brown: "Scratch VO"
    yellow: "From Audio Library"
  track_color_nomatch_label: "Temp Material"

frame_rate: '24'
shot_name_regex: '[\d]{3}_[a-zA-Z0-9]+_shot_[\w]+.[a-zA-Z0-9]+'
shot_name_resubs: [
  { 'pattern': r'\(.*\)', 'replacement': r'' },
  { 'pattern': r'_SB', 'replacement': r'' },
  { 'pattern': r"\_\d\d\d\d\d\d\d\d", 'replacement': r''},
  ]

MOVIE_FILE_SUFFIXES: {'mov'}
IMAGE_FILE_SUFFIXES: {"png", "jpg"}

# Here are the values for the provided burnins
CONFORMSHOT_BURNIN_PREFIX: "shot_"
CONFORMSCENE_BURNIN_PREFIX: "scene_"

# Here are the values for the Premiere test .xml file
# CONFORMSHOT_BURNIN_PREFIX: "Sc_"
# CONFORMSCENE_BURNIN_PREFIX: "seq"
