name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  actions: write
  checks: write

jobs:
  coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest] # ["ubuntu-latest", "windows-latest", "macos-latest"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Python ${{ matrix.python-version }} with uv
        uses: ./.github/actions/setup-python-with-uv
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: |
          uv run pytest --junitxml=pytest.xml --cov-report=term-missing --cov=fcp7xml_to_unreal tests/ | tee pytest-coverage.txt

      - name: Coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
          unique-id-for-comment: ${{ matrix.python-version }}-${{ matrix.os }}
          title: Coverage for Python ${{ matrix.python-version }} on ${{ matrix.os }}

  update-badge:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"] # ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Python ${{ matrix.python-version }} with uv
        uses: ./.github/actions/setup-python-with-uv
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: |
          uv run pytest --junitxml=pytest.xml --cov-report=term-missing --cov=fcp7xml_to_unreal tests/ | tee pytest-coverage.txt

      - name: Coverage comment
        id: coverage
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
          hide-comment: true

      - name: Update README
        run: |
          sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n${{ steps.coverage.outputs.coverageHtml }}\n<!-- Pytest Coverage Comment:End -->' ./README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: update coverage badge'
          file_pattern: README.md
