name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  actions: write
  checks: write

jobs:
  coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest] # ["ubuntu-latest", "windows-latest", "macos-latest"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Python ${{ matrix.python-version }} with uv
        uses: ./.github/actions/setup-python-with-uv
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: |
          uv run pytest --junitxml=pytest.xml --cov-report=term-missing --cov=fcp7xml_to_unreal tests/ | tee pytest-coverage.txt
